import express from 'express';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs/promises';
import { v4 as uuidv4 } from 'uuid';

const router = express.Router();
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const dataPath = join(__dirname, '..', 'data', 'blogs.json');

// Helper to read blogs data
async function readBlogsData() {
  try {
    const data = await fs.readFile(dataPath, 'utf-8');
    return JSON.parse(data);
  } catch (error) {
    return { blogs: [], lastPostTime: null };
  }
}

// Helper to write blogs data
async function writeBlogsData(data) {
  await fs.writeFile(dataPath, JSON.stringify(data, null, 2));
}

// GET all blogs
router.get('/', async (req, res) => {
  try {
    const data = await readBlogsData();
    res.json(data.blogs);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch blogs' });
  }
});

// GET single blog by ID
router.get('/:id', async (req, res) => {
  try {
    const data = await readBlogsData();
    const blog = data.blogs.find(b => b.id === req.params.id);
    if (!blog) {
      return res.status(404).json({ error: 'Blog not found' });
    }
    res.json(blog);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch blog' });
  }
});

// POST create new blog
router.post('/', async (req, res) => {
  try {
    const data = await readBlogsData();
    const newBlog = {
      id: uuidv4(),
      title: req.body.title || 'Untitled Blog',
      slug: req.body.slug || generateSlug(req.body.title || 'untitled'),
      metaDescription: req.body.metaDescription || '',
      content: req.body.content || '',
      originalContent: req.body.originalContent || req.body.content || '',
      tags: req.body.tags || [],
      category: req.body.category || 'General',
      keyword: req.body.keyword || '',
      status: req.body.status || 'draft',
      isAutoGenerated: req.body.isAutoGenerated || false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      publishedAt: null,
      views: 0
    };
    
    data.blogs.unshift(newBlog);
    await writeBlogsData(data);
    res.status(201).json(newBlog);
  } catch (error) {
    res.status(500).json({ error: 'Failed to create blog' });
  }
});

// PUT update blog
router.put('/:id', async (req, res) => {
  try {
    const data = await readBlogsData();
    const index = data.blogs.findIndex(b => b.id === req.params.id);
    
    if (index === -1) {
      return res.status(404).json({ error: 'Blog not found' });
    }
    
    const updatedBlog = {
      ...data.blogs[index],
      ...req.body,
      id: data.blogs[index].id, // Preserve ID
      createdAt: data.blogs[index].createdAt, // Preserve creation date
      updatedAt: new Date().toISOString()
    };
    
    data.blogs[index] = updatedBlog;
    await writeBlogsData(data);
    res.json(updatedBlog);
  } catch (error) {
    res.status(500).json({ error: 'Failed to update blog' });
  }
});

// PUT publish blog
router.put('/:id/publish', async (req, res) => {
  try {
    const data = await readBlogsData();
    const index = data.blogs.findIndex(b => b.id === req.params.id);
    
    if (index === -1) {
      return res.status(404).json({ error: 'Blog not found' });
    }
    
    data.blogs[index].status = 'published';
    data.blogs[index].publishedAt = new Date().toISOString();
    data.blogs[index].updatedAt = new Date().toISOString();
    data.lastPostTime = new Date().toISOString();
    
    await writeBlogsData(data);
    res.json(data.blogs[index]);
  } catch (error) {
    res.status(500).json({ error: 'Failed to publish blog' });
  }
});

// PUT unpublish blog
router.put('/:id/unpublish', async (req, res) => {
  try {
    const data = await readBlogsData();
    const index = data.blogs.findIndex(b => b.id === req.params.id);
    
    if (index === -1) {
      return res.status(404).json({ error: 'Blog not found' });
    }
    
    data.blogs[index].status = 'draft';
    data.blogs[index].updatedAt = new Date().toISOString();
    
    await writeBlogsData(data);
    res.json(data.blogs[index]);
  } catch (error) {
    res.status(500).json({ error: 'Failed to unpublish blog' });
  }
});

// DELETE blog
router.delete('/:id', async (req, res) => {
  try {
    const data = await readBlogsData();
    const index = data.blogs.findIndex(b => b.id === req.params.id);
    
    if (index === -1) {
      return res.status(404).json({ error: 'Blog not found' });
    }
    
    data.blogs.splice(index, 1);
    await writeBlogsData(data);
    res.json({ message: 'Blog deleted successfully' });
  } catch (error) {
    res.status(500).json({ error: 'Failed to delete blog' });
  }
});

// Helper function to generate slug
function generateSlug(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .substring(0, 60);
}

export default router;
