import express from 'express';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs/promises';
import { runScheduledPost, getSchedulerStatus } from '../services/scheduler.js';

const router = express.Router();
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const settingsPath = join(__dirname, '..', 'data', 'settings.json');
const blogsPath = join(__dirname, '..', 'data', 'blogs.json');

// Helper to get restart function from app
function getRestartScheduler(req) {
  return req.app.get('restartScheduler');
}

// GET scheduler status
router.get('/status', async (req, res) => {
  try {
    const status = await getSchedulerStatus();
    res.json(status);
  } catch (error) {
    res.status(500).json({ error: 'Failed to get scheduler status' });
  }
});

// POST trigger manual post
router.post('/trigger', async (req, res) => {
  try {
    const result = await runScheduledPost();
    res.json(result);
  } catch (error) {
    console.error('Manual trigger error:', error);
    res.status(500).json({ error: error.message || 'Failed to trigger post' });
  }
});

// PUT toggle auto-posting
router.put('/toggle', async (req, res) => {
  try {
    const settingsData = await fs.readFile(settingsPath, 'utf-8');
    const settings = JSON.parse(settingsData);
    
    settings.autoPostEnabled = !settings.autoPostEnabled;
    
    await fs.writeFile(settingsPath, JSON.stringify(settings, null, 2));
    
    // Restart scheduler with new settings
    const restartScheduler = getRestartScheduler(req);
    if (restartScheduler) {
      await restartScheduler();
    }
    
    res.json({ 
      autoPostEnabled: settings.autoPostEnabled,
      message: settings.autoPostEnabled ? 'Auto-posting enabled' : 'Auto-posting disabled'
    });
  } catch (error) {
    res.status(500).json({ error: 'Failed to toggle auto-posting' });
  }
});

// PUT update interval
router.put('/interval', async (req, res) => {
  try {
    const { intervalMinutes } = req.body;
    
    if (!intervalMinutes || intervalMinutes < 1) {
      return res.status(400).json({ error: 'Invalid interval' });
    }
    
    const settingsData = await fs.readFile(settingsPath, 'utf-8');
    const settings = JSON.parse(settingsData);
    
    settings.postIntervalMinutes = intervalMinutes;
    
    await fs.writeFile(settingsPath, JSON.stringify(settings, null, 2));
    
    // Restart scheduler with new interval
    const restartScheduler = getRestartScheduler(req);
    if (restartScheduler) {
      await restartScheduler();
      console.log(`[Scheduler] Interval changed to ${intervalMinutes} minutes, scheduler restarted`);
    }
    
    res.json({ 
      postIntervalMinutes: settings.postIntervalMinutes,
      message: `Interval updated to ${intervalMinutes} minutes`
    });
  } catch (error) {
    res.status(500).json({ error: 'Failed to update interval' });
  }
});

// GET posting history
router.get('/history', async (req, res) => {
  try {
    const blogsData = await fs.readFile(blogsPath, 'utf-8');
    const { blogs } = JSON.parse(blogsData);
    
    const publishedBlogs = blogs
      .filter(b => b.status === 'published' && b.isAutoGenerated)
      .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt))
      .slice(0, 20);
    
    res.json(publishedBlogs);
  } catch (error) {
    res.status(500).json({ error: 'Failed to get posting history' });
  }
});

export default router;
